### ISSUE TITLE
Checking Origin

### ISSUE THREAD

**Issue by DestruidorPT** [passwordless-lib/fido2-net-lib#220]
I was exploring the code, I have a question relative to the Origin, when an application sends the Authenticator Assertion Response, the origin of this response needs to be checked with the origin in the Authenticator Assertion request, correct?

Exemple:
- In the case of Web, a user requests to authenticate he has Origin “domain.com”, and then he sends a challenge signed with Origin “domain.com”, the origin of the request and the origin sent with the challenge signed must match.
- In the case of Android, a user requests to authenticate he has Origin “android:apk-key-hash:LBpmHljqwJJLdXVNpjfdA”, and then he sends a challenge signed with Origin “android:apk-key-hash:LBpmHljqwJJLdXVNpjfdA”, the origin of the request and the origin sent with the challenge signed must match.

So if the origin of the request must be the same as the origin sent with the challenge signed, it wouldn’t be better if instead of putting Origin in the Fido2Configuration, put in the function MakeAssertionAsync? This way Fido2Configuration doesn’t have to change every time a different origin comes, for example, the android sends a different origin from the web.

**Comment by DestruidorPT** [comment]
My suggestion is this [DestruidorPT/fido2-net-lib](https://github.com/DestruidorPT/fido2-net-lib/commit/9d5cc3a425ceec34980cf883e9d35eaa9dd7d058), and I add a parameter on Fido2Configuration where we can configure what origins are allowed on FIDO2, this way if stop another app to access if the origin doesn't match, I also allowed to be empty in case someone wants the FIDO2 to be access from any app.

**Comment by DestruidorPT** [comment]
I have corrected the missing origin in the test and in the demo, check my suggestion, if you agree I do a pull request.
[DestruidorPT/fido2-net-lib](https://github.com/DestruidorPT/fido2-net-lib)

**Comment by Hinton** [comment]
We ran into the same issue while trying to add support for our Android application. The library is currently limited to a single origin which gets set during initialization.

Before I start looking into this in-depth, I wanted to check with the maintainers if you are open to having a community PR to add support for multiple origins?

Since we ideally want to maintain backwards compatibility with the current API, I think we can add a new optional parameter for `expectedOrigin` to the methods, which would take precedence over the `Fido2Configuration.Origin` value. Alternatively add a new setting `Origins` to the `Fido2Configuration` and fall back to `Origin` if it’s missing.

Does this seem like a reasonable approach @abergs? If so I would be happy to look into implement support for this.

**Comment by aseigler** [comment]
> Before I start looking into this in-depth, I wanted to check with the maintainers if you are open to having a community PR to add support for multiple origins?

Of course!

**Comment by abergs** [comment]
@Hinton I think that seems like a very reasonable approach. I especially endorse the backwards compatibility thought.
I will close this ticket. See #237 for further discussions.
