### ISSUE TITLE
Breaking: REQUIRE NET 5.0 MINIMUM? (Please vote)

### ISSUE THREAD

**Issue by abergs** [passwordless-lib/fido2-net-lib#246]
Hello all,

In an effort to make the development easier and keeping up with the times (#214) we are thinking of requiring .NET 5.0.
My worry is that it hinders fido2 adoption (making the library unusable for legacy apps) -- but I want to hear it from consumers directly.

Please provide input and vote (👍 / 👎).

**Comment by MichaelGrafnetter** [comment]
IMO, WebAuthn will mostly be used by modern ASP.NET Core apps where .NET 5 should not be an issue. The added bonus of using a Microsoft-supported library is huge, especially in regards to potential security issues and licensing. One could also imagine having an abstraction layer that would load one of these libraries based on the .NET framework version, but that would probably be too complicated and not worth it.

**Comment by iamcarbon** [comment]
We should also keep in mind that the new .NETCORE support policy only provides 3 years of LTS support for major releases. 
While .NET 6.0 will be entering into LTS next month and supported into 2024, .NETCORE 3.1 will end support on December 3, 2022. All prior .NETCORE frameworks have already gone out of support. 

For a security focused library, it is critical customers are also running on secure and supported framework. By supporting legacy apps, we may doing a disservice leaving end-users vulnerability to unpatched critical bugs.

**Comment by mackie1001** [comment]
I'm down with this as we're intending to upgrade to 6 from 3.1 (we always go with LTS versions) as soon as it's available (which is next week). I think supporting the prevailing LTS versions should be the general rule of thumb but it makes sense to go up to 5 or 6 early to gain access to the new CBOR lib.

**Comment by aseigler** [comment]
From my count we are now over a month with no voiced opposition.

**Comment by abergs** [comment]
@aseigler Indeed!
The result from the voting is 11-0. **We therefore push forward with .NET 5 as requirement.**

Thank you everyone who voted and chimed in with opinions.

**Comment by MichaelGrafnetter** [comment]
Hi, although the issue is already closed and I voted for upgrade, I am aware of one breaking issue, which is Microsoft Active Directory Federation Services (ADFS) FIDO2 MFA providers, like the [NEOS SDI ADFS MFA](https://github.com/neos-sdi/adfsmfa).
ADFS is a built-in Windows component running on top of .NET Framework. Its authentication plugins thus also need to target .NET Framework. Moreover, all such plugins must be located in Global Assembly Cache (GAC). That is actually the reason why that project is not using the official FIDO2 NuGet packages, as the DLLs are not strong-name signed.
