### ISSUE TITLE
Demo: Logic unclear around checking for unique credentials

### ISSUE THREAD

**Issue by tillig** [passwordless-lib/fido2-net-lib#285]
I'm looking at the demo site in the [`MakeCredential` controller method](https://github.com/passwordless-lib/fido2-net-lib/blob/db931bdba2/Demo/Controller.cs#L103) and I'm not sure if I'm misunderstanding something fundamental or if there's maybe some questionable logic.

In that controller method it uses a callback to verify if a given credential is unique to a user.

```c#
// 2. Create callback so that lib can verify credential id is unique to this user
IsCredentialIdUniqueToUserAsyncDelegate callback = static async (args, cancellationToken) =>
{
  var users = await DemoStorage.GetUsersByCredentialIdAsync(args.CredentialId, cancellationToken);
  if (users.Count > 0)
    return false;

  return true;
};

// 2. Verify and make the credentials
var success = await _fido2.MakeNewCredentialAsync(attestationResponse, options, callback, cancellationToken: cancellationToken);
```

(And, yes, there are two # 2 steps in there.)

The thing is, [looking at the way the example storage is structured](https://github.com/passwordless-lib/fido2-net-lib/blob/db931bdba20aadc0743184fc9b0383a88b56ce02/Src/Fido2/DevelopmentInMemoryStore.cs#L54), _every_ registered authenticator inherently has a user connected; and the callback above effectively says "if there are any users connected, it's not a unique credential."

It appears that this could basically be `DemoStorage.GetCredentialById` and if there's a credential registered with that ID, it's implicitly not unique. There's no value in doing a subsequent user lookup.

**Is it really about determining if the authenticator is unique _to the user_ or is it more about determining if the authenticator is unique _in the system_?**

It may just be the naming is confusing me but it appears the intent is to ensure you don't have the same authenticator attached to multiple users, so if it's registered _at all_ that would logically mean it's attached to a user and you're done.

**Is there something I'm misunderstanding?**

I'm trying to model this so we can store things in Cosmos DB and the extra lookups will cost Request Units. If it's required for some use case, no problem; but if we can shortcut it, it actually saves time and money.

**Comment by aseigler** [comment]
This one is squarely in the wheelhouse of @abergs.

**Comment by abergs** [comment]
Ah! Some lovely and very old lines of code :) This reminds me that the examples in the readme should probably get a touch up.

> The thing is, [looking at the way the example storage is structured](https://github.com/passwordless-lib/fido2-net-lib/blob/db931bdba20aadc0743184fc9b0383a88b56ce02/Src/Fido2/DevelopmentInMemoryStore.cs#L54), every registered authenticator inherently has a user connected; and the callback above effectively says "if there are any users connected, it's not a unique credential."
It appears that this could basically be DemoStorage.GetCredentialById and if there's a credential registered with that ID, it's implicitly not unique. There's no value in doing a subsequent user lookup.

Yes, that would often be a fair assumption.
As per the  [spec](https://www.w3.org/TR/webauthn-2/#sctn-registering-a-new-credential)

>Check that the [credentialId](https://www.w3.org/TR/webauthn-2/#credentialid) is not yet registered to any other user. If registration is requested for a credential that is already registered to a different user, the [Relying Party](https://www.w3.org/TR/webauthn-2/#relying-party) SHOULD fail this [registration ceremony](https://www.w3.org/TR/webauthn-2/#registration-ceremony), or it MAY decide to accept the registration, e.g. while deleting the older registration.

There are some leeway for the app developer to do different things.

> Is it really about determining if the authenticator is unique to the user or is it more about determining if the authenticator is unique in the system?

Don't take my word as laws of nature, but I think you might make a case for not failing re-registering the same credential to the same user. But as the spec says, you might allow re-registering credentials to the same user (because of UX etc). Our demo obviously fails you, but the demo code is not perfect. It's indeed only a demo.

> Is there something I'm misunderstanding?

There are quite some things to think about, even though we've hidden most of the complexities. But I think you're on a good path.

Would be interesting to hear how your deployment on top of Cosmos is working.
We're running the hosted version [passwordless.dev](https://passwordless.dev) on Azure as well.

**Comment by tillig** [comment]
This helps a lot, thank you! I've read through the spec, but it's a lot to unpack so I appreciate the clarification there.

We're in the design phase of things right now, trying to create a unified user + resource + device model that combines functionality from:

- This library
- Identity Server
- ASP.NET Identity
- [SCIM](http://www.simplecloud.info/)

The concepts overlap a lot and we have enough unique need in this area that it was worth doing a POC to see what it would take to implement a service that would support all of those things so we can expose the functionality of each but on top of a single backing data store. If it turns out we decide to go forward into production with it, we'll likely end up running it in a decent sized Kubernetes cluster in Azure.

We figured Cosmos was a good backing store for the unified data model due to the extensibility SCIM requires, and a lot of the data access patterns work pretty well without requiring high request units. I imagine when we get past POC level we'd still need to analyze and tune a bit, but it's pretty early on the road at the moment so we're still at "get it working" stages.
