### ISSUE TITLE
does it has no limitataion for this library?

### ISSUE THREAD

**Issue by dennischchch** [passwordless-lib/fido2-net-lib#298]
does it have some limitation if I hosting the server using the library myself? I saw the demo page mentioned that Up to 50.000 accounts for free plan.

**Comment by abergs** [comment]
Hello @dennischchch. This library itself has no limitations. However, along side the library we also provide a API Service (passwordless.dev) that makes it even easier to get started using WebAuthn,
The limit you are referring to is for the Free Plan on that API service. However, the API Service can serve a lot more users on the paid plans.

If you want to configure and operate a WebAuthn service yourself, you should use this library as it gives you complete control of everything.
If you 'just want to add WebAuthn to your app' you probably want to use the API Service since it will be faster and operated by us. If you ever change your mind, you can always migrate between away from the API Service to using the library on your own server.
