### ISSUE TITLE
Transmit attestationObject as array instead of base64 string

### ISSUE THREAD

**Issue by Regenhardt** [passwordless-lib/fido2-net-lib#369]
Trying to send the `PublicKeyCredential` (response from `credentials.create`), specifically the `.response.attestationObject`, and I just realized to do that I have to   
1) put it into Uint8Array,  
2) convert to string and  
3) btoa the thing  
because the property on the model is expected as base64url-encoded, even though the model then holds a byte[] again.

Why not just expect a byte[] directly, as that is basically what the browser provides anyway, so we don't need to first encode it just so dotnet can then decode it again, also making the payload bigger?  
Would prefer to just 1) put it into Uint8Array and send the thing.

Edit: This also applies to the `PublicKeyCredential.rawId`, [which is an ArrayBuffer](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential) so would more intuitively be transmitted as `byte[]`.

**Comment by abergs** [comment]
Hi @Regenhardt,

The library does not necessarily dictate how you transmit data from your front end to your back end.

As you mention the [AttestionObject model expects at byte[].](https://github.dev/passwordless-lib/fido2-net-lib/blob/5e725648ac3232c8653bf7f6861e992109f1a53a/Src/Fido2.Models/AuthenticatorAttestationRawResponse.cs#L30)

As to why we are serializing the payloads when transmitting them is because we use JSON in all our demo's (it's by far the most common content-type for APIs) and [json do not support byte arrays](https://stackoverflow.com/questions/20706783/put-byte-array-to-json-and-vice-versa). 

To ensure things "work out of the box" for most people, we have decorated the model with JsonConverters. These do not affect you if you choose to use any other content type that supports byte[].

And specifically, since the WebAuthn specification uses Base64Url encoding elsewhere, we opt to reuse it to avoid mixing too much base64 and base64url to make it less error prone.

**Comment by Regenhardt** [comment]
Wouldn't a byte[] in json just be a number[] because that's what js uses? Or can there be problems regarding int/byte-conversion?

**Comment by abergs** [comment]
If you wish, you can do that. But the size would be a lot larger, which is way base64 is used.

I think Jon Skeet explains it better than I can: https://stackoverflow.com/a/67156941
