### ISSUE TITLE
AuthenticatorSelection.ResidentKey not in released version

### ISSUE THREAD

**Issue by merijndejonge** [passwordless-lib/fido2-net-lib#373]
Hello,
I'm using fido2-net-lib version 3.0.1. I'm trying to build my own project based on the example code https://github.com/passwordless-lib/fido2-net-lib/tree/master/Demo. However, my code doesn't compile because in the nuget package there is no property ResidentKey in AuthenticatorSelection. If I browse the source code on github I see that this property is available. It is a bit confusing for a new user, like me, that the example code does not work in my own project. When can we expect a corresponding nuget package? 

Thanks

**Comment by abergs** [comment]
Hi,

Since we merge changes quite often, master branch **often** contain code that is not released yet.
We release on a schedule that make sense for us and we try to balance the amount of releases and the amount of breaking changes we introduce.

If you want to see the source code (and demo) for the 3.0.1 version it is available on github, under the 3.0.1 tag: https://github.com/passwordless-lib/fido2-net-lib/tree/v3.0.1

Sorry about that confusion, but currently we want to get some more features in before we release a 4.0.0 that will include among other things the new AuthenticatorSelection.
