### ISSUE TITLE
Does this/Can it work on Asp.net 4.8?

### ISSUE THREAD

**Issue by kevinDVault** [passwordless-lib/fido2-net-lib#378]
Have an older project running on Framework 4.8. (not yet ported to Core as it's not a trivial task). Would be great to get FIDO/password-less working on legacy apps.

Any way to get this working?

thanks

Edit: never mind. read a previous post where you voted and based everything on Net5. Shame but this stack is no use to us - We'll work on an alternate solution.

**Comment by abergs** [comment]
@kevinDVault Yes, because of the maintenance burden this repo cannot maintain support for older .net versoins.

An other way to solve your issue is to use [passwordless.dev ](https://www.passwordless.dev/), which I work on to make sure all apps (regardless of platform) can move to passwordless authentication.

**Comment by kevinDVault** [comment]
Ok and understand (but not like!).

Passwordless.dev – Not a runner until you publish the commercials on it – what’s the cost, thresholds/limits,  SLA (guaranteed uptime and availability) and lots more. No business can commit to building a feature into their product without first understand this.

thanks

**Comment by abergs** [comment]
@kevinDVault Agreed, pricing will be available in end of Q1 for passwordless.dev.
