### ISSUE TITLE
fully qualified origin not equal to fully qualified original origin (1)

### ISSUE THREAD

**Issue by cwc9001** [passwordless-lib/fido2-net-lib#381]
I have a .net 7 api for the backend and an angular app for the frontend. Everything works fine locally. They are both running on localhost. When I deploy them the angular app is running https://fakeurl.com and the api is on https://api.fakeurl.com. I have fakeurl.com as the ServerDomain in the configuration and I have both urls in the Origins. When I try to register a credential, it asks for my fingerprint like it should but then it gives me the error fully qualified origin https://fakeurl.com of https://fakeurl.com not equal to fully qualified original origin (1)

**Comment by Regenhardt** [comment]
Turns out the ServerDomain is also the domain checked against the credential. Something like [this](https://gitlab.com/Regenhardt/fido2-webauthn-blazor/-/blob/master/Server/Controllers/UserController.cs#L79) (using this [FidoFactory](https://gitlab.com/Regenhardt/fido2-webauthn-blazor/-/blob/master/Server/FidoFactory.cs)) might fix it. Had the same problem, thinking how to gracefully change it, maybe add something about this to the inline documentation once my current PR is through.

**Comment by cwc9001** [comment]
That worked. Thank you very much.
