### ISSUE TITLE
Tweaking .editorconfig and dotnet format to support patterns we use

### ISSUE THREAD

**Issue by abergs** [passwordless-lib/fido2-net-lib#423]
I've only played with this a little bit but;

I want to get to a place where we can run `dotnet format` as part of the CI/CD pipeline. Currently, this breaks some of the patterns we use, like:

* Same line switch clauses
* Columnar alignment in enums
* Anything else?

Would be interesting to see if we can tweak our .editorconfig to support us.

**Comment by abergs** [comment]
@iamcarbon Got any ideas?

Also - not directed to you Jason, but in general: Just to be clear, I won't be able to accept any PR's that have run `dotnet format` until we figure out the rules. And once we have the config, I will need to run it to avoid the review hangover.

**Comment by iamcarbon** [comment]
Just ran and reviewed the formatting changes locally -- and broke your advice and submitted a PR with the changes (which should take < 5 minutes to review). All the formatting changes look good, except the removal of column alignment -- which helps when we add inline documentation. It will be sad to see these lost and I don't see any trivial way to prevent these from getting changed.

Rather than running dotnet format in CI, would it be sufficient to run every release -- and do a quick review? The diffs are easy to review and allow us to keep our custom formatting.

I would still consider continuing to update our .editorconfig rules to enforce coding style -- perhaps elevating certain style issues to errors.

I'm not bothered by any of the current styles -- other than using var when the type isn't apparent.

Examples of things that would be sad to see changed:

<img width="396" alt="Screenshot 2023-08-23 at 2 07 23 PM" src="https://github.com/passwordless-lib/fido2-net-lib/assets/7537/203cded9-eea1-43a0-9542-9aa70d2d1252">

<img width="658" alt="Screenshot 2023-08-23 at 2 07 43 PM" src="https://github.com/passwordless-lib/fido2-net-lib/assets/7537/1aa71f00-8307-4488-a142-ceb488c7835b">

<img width="1039" alt="Screenshot 2023-08-23 at 2 09 17 PM" src="https://github.com/passwordless-lib/fido2-net-lib/assets/7537/86dcd643-373b-4b5d-8b75-a630cb3a7030">

**Comment by iamcarbon** [comment]
@abergs Let me know if there were any current coding styles / patterns / formatting in the current codebase you'd like to see cleaned up / enforced as well. I've taken at least 10 passes over all the files now, and nothing big is standing out.

**Comment by abergs** [comment]
Closed in #425
