### ISSUE TITLE
Missing NuGet package

### ISSUE THREAD

**Issue by Nk185** [passwordless-lib/fido2-net-lib#532]
It seems like `Src/Fido2.Ctap2` is not pushed NuGet...
As a temporary workaround, it's possible to copy-paste the code directly into the project. But it would be really nice if this gets fixed and Ctap2 is available on NuGet.

**Comment by abergs** [comment]
@Nk185 What's your use case for the Ctap2 module?

**Comment by pdugre** [comment]
@abergs Went through the same issue here. I'm basically trying to implement a native relying party (AKA use the WebAuthn platform API for a native app instead of a website), but from what I've seen the current state of the nuget doesn't implement the client-side APIs. I thought the Ctap2 module could be of use

**Comment by abergs** [comment]
@pdugre I would expect native RP API's to expose API's similar to WebAuthn and not CTAP. On what platform are you building?

**Comment by abergs** [comment]
IIRC MacOS is returning (almost) WebAuthn like responses, so I don't think you would need CTAP. CTAP is the protocol used between platforms and authenticators (e.g. a security key) and I wouldn't expect app devs to use it
